name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main
    #paths:
     # - 'src/backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: "exo.container-registry.com"
          username: ${{ secrets.EXO_REGISTRY_EMF_EMAIL }}
          password: ${{ secrets.EXO_REGISTRY_EMF }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/backend
          push: true
          tags: exo.container-registry.com/c213-emf/todo-app-voel:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webApp-300722-210-voeffray-lucielle-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5afd5ad6249a402f9625e30a1f17fc58 }}
        images: 'exo.container-registry.com/c213-emf/todo-app-voel:latest'
