# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webApp-300722-210-voeffray-lucielle-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://exo.container-registry.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_5d95e9a3059b4c778630c94874af8bf6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e8d5bc93aaee4dc8bc3328683eec1c06 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: exo.container-registry.com/${{ secrets.AzureAppService_ContainerUsername_5d95e9a3059b4c778630c94874af8bf6 }}/c213-emf/todo-app-voel:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webApp-300722-210-voeffray-lucielle-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5afd5ad6249a402f9625e30a1f17fc58 }}
        images: 'exo.container-registry.com/${{ secrets.AzureAppService_ContainerUsername_5d95e9a3059b4c778630c94874af8bf6 }}/c213-emf/todo-app-voel:${{ github.sha }}'